export const SYMBOLS = [
  {
    code: '100.NDX',
    displaySymbol: 'NDX',
    name: '纳斯达克',
    region: 'US',
    currency: 'USD',
    tencent: 'usIXIC',
    sina: '.ixic',
  },
  {
    code: '100.SPX',
    displaySymbol: 'SPX',
    name: '标普500',
    region: 'US',
    currency: 'USD',
    tencent: 'usINX',
    sina: '.inx',
  },
  {
    code: '1.000001',
    displaySymbol: 'SSE',
    name: '上证指数',
    region: 'CN',
    currency: 'CNY',
    tencent: 'sh000001',
  },
  {
    code: '0.399006',
    displaySymbol: 'ChiNext',
    name: '创业板指',
    region: 'CN',
    currency: 'CNY',
    tencent: 'sz399006',
  },
  {
    code: '1.000688',
    displaySymbol: 'STAR 50',
    name: '科创50',
    region: 'CN',
    currency: 'CNY',
    tencent: 'sh000688',
  },
  {
    code: '124.HSTECH',
    displaySymbol: 'HSTECH',
    name: '恒生科技指数',
    region: 'HK',
    currency: 'HKD',
    tencent: 'hkHSTECH',
  },
]
